-- Run this in Supabase SQL Editor before importing data.
-- This table is read-only for public visitors through Row Level Security.

create table if not exists public.places (
  id integer generated by default as identity primary key,
  nama text not null,
  kategori text,
  label text,
  deskripsi text,
  alamat text,
  latitude double precision,
  longitude double precision,
  fasilitas text,
  harga_tiket text,
  jam_operasional text,
  telepon text,
  url text unique,
  url_gambar text,
  tags text,
  likes integer default 0,
  author text,
  sumber text,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

create index if not exists places_kategori_idx on public.places (kategori);
create index if not exists places_likes_idx on public.places (likes desc);
create index if not exists places_nama_idx on public.places (nama);

alter table public.places enable row level security;

drop policy if exists "public can read places" on public.places;
create policy "public can read places"
on public.places
for select
to anon
using (true);

grant usage on schema public to anon;
grant select on public.places to anon;
